### ISSUE TITLE
just stoped working

### ISSUE THREAD

**Issue by OM3GA6400** [simalei/nong-manager#2]
![image](https://github.com/simalei/nong-manager/assets/98067930/39ba1c82-3458-4ff1-aa56-31db2e461299)

**Comment by simalei** [comment]
Hello, sorry for taking so long to answer.
This error happens due to the changes in SongFileHub's API in which they changed some of the endpoints from which NONG manager fetches info about the song.
I will most likely archive this repo until I find time to rewrite it,
